"""
LLFF (Local Light Field Fusion) Dataset Loader.

Loads images, camera poses, and depth bounds from the LLFF dataset format
(e.g., Fern, Flower, Fortress). Each scene contains a poses_bounds.npy file
generated by COLMAP + LLFF preprocessing, storing per-frame camera-to-world
matrices, intrinsics, and near/far depth bounds.

Coordinate Convention:
    LLFF native (DRB): +X Down, +Y Right, +Z Backwards (camera looks along -Z).
    NeRF / OpenGL (RUB): +X Right, +Y Up, +Z Backwards (camera looks along -Z).
    This loader converts from LLFF to NeRF convention during loading.

Reference: Mildenhall et al. 2019 (LLFF), Mildenhall et al. 2020 (NeRF).
"""

import os

import imageio.v3 as iio
import numpy as np


def load_llff_data(basedir, factor=1, recenter=True):
    """Load a scene from the LLFF dataset format.

    Args:
        basedir: Root directory of the scene (e.g., './nerf_llff_data/fern').
        factor: Downsample factor (1 = original resolution, 2 = half, etc.).
        recenter: If True, recenter poses so the average pose is at the origin.

    Returns:
        images:       np.ndarray, shape [N, H, W, 3], float32, range [0, 1]. RGB.
        poses:        np.ndarray, shape [N, 4, 4], float32. Camera-to-world matrices.
        render_poses: np.ndarray, shape [120, 4, 4], float32. Spiral poses for rendering.
        hwf:          list [H, W, focal]. Image dimensions and focal length.
        i_split:      list of 3 np.ndarrays, indices for [train, val, test] splits.
    """
    poses_raw, bounds, hwf_raw = _load_poses_bounds(basedir)
    # poses_raw: [N, 3, 4] c2w in LLFF convention (+Z forward, +Y down)
    # bounds:    [N, 2] per-camera [near, far]
    # hwf_raw:   [3] original [H, W, focal]

    # Load images and optionally downsample
    images, hwf = _load_images(basedir, factor, hwf_raw)
    N = images.shape[0]
    assert N == poses_raw.shape[0], "Image count must match pose count."

    # Convert LLFF coordinate convention to NeRF/OpenGL convention
    # LLFF (DRB): [down, right, backwards, t] -> NeRF (RUB): [right, up, backwards, t]
    poses_raw = poses_raw[:, :3, :4]
    poses_raw = np.concatenate([
        poses_raw[:, :, 1:2],      # right  (LLFF col 1)
        -poses_raw[:, :, 0:1],     # up = -down  (negated LLFF col 0)
        poses_raw[:, :, 2:],       # backwards + translation  (LLFF cols 2-3, unchanged)
    ], axis=2)

    # Recenter: align average camera pose to the origin
    if recenter:
        poses_raw = _recenter_poses(poses_raw)

    # Pad to [N, 4, 4] homogeneous form
    poses = np.zeros((N, 4, 4), dtype=np.float32)
    poses[:, :3, :4] = poses_raw
    poses[:, 3, 3] = 1.0

    # Scale scene so that near bound ≈ 1.0
    # This normalization helps the MLP learn effectively
    near_original = bounds.min()
    scale_factor = 1.0 / (near_original * 0.75)
    poses[:, :3, 3] *= scale_factor
    bounds *= scale_factor

    # Generate spiral render poses for novel view synthesis
    render_poses = _generate_spiral_poses(poses, bounds)

    # Train/val split: every 8th image for validation (standard LLFF convention)
    i_test = np.arange(0, N, 8)
    i_train = np.array([i for i in range(N) if i not in i_test])
    i_val = i_test.copy()
    i_split = [i_train, i_val, i_test]

    H, W, focal = hwf

    return images, poses, render_poses, [H, W, focal], i_split


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _load_poses_bounds(basedir):
    """Parse poses_bounds.npy into camera poses, depth bounds, and intrinsics.

    The file stores one row per image, each row has 17 values:
        [3x5 pose matrix flattened (15), near (1), far (1)]
    The 3x5 matrix is [3x3 rotation | 3x1 translation | 3x1 hwf].

    Returns:
        poses: [N, 3, 4] camera-to-world matrices (LLFF convention).
        bounds: [N, 2] per-camera [near, far] depth bounds.
        hwf: [3] original [H, W, focal] from the first camera.
    """
    poses_bounds = np.load(os.path.join(basedir, "poses_bounds.npy"))
    # Shape: [N, 17]

    # Reshape the first 15 columns into [N, 3, 5]
    poses_hwf = poses_bounds[:, :15].reshape(-1, 3, 5)

    # Extract camera-to-world [N, 3, 4] and intrinsics [N, 3]
    poses = poses_hwf[:, :, :4]   # [N, 3, 4]: rotation + translation
    hwf_all = poses_hwf[:, :, 4]  # [N, 3]: each row is [H, W, focal] per camera

    # Use intrinsics from the first camera (all cameras share the same intrinsics)
    hwf = hwf_all[0]  # [H, W, focal]

    # Depth bounds
    bounds = poses_bounds[:, 15:17]  # [N, 2]: [near, far]

    return poses.astype(np.float32), bounds.astype(np.float32), hwf.astype(np.float32)


def _load_images(basedir, factor, hwf_raw):
    """Load images from the images/ directory and optionally downsample.

    Always reads from the original-resolution images/ folder, then
    performs in-code downsampling if factor > 1. This is consistent
    with load_blender.py and works for any integer factor.

    Args:
        basedir: Scene root directory.
        factor: Downsample factor (1 = original, 2 = half, etc.).
        hwf_raw: Original [H, W, focal] from poses_bounds.npy.

    Returns:
        images: [N, H, W, 3] float32 in [0, 1].
        hwf: [H, W, focal] at the (possibly downsampled) resolution.
    """
    img_dir = os.path.join(basedir, "images")
    if not os.path.exists(img_dir):
        raise FileNotFoundError(f"Image directory not found: {img_dir}")

    # Sort to ensure consistent ordering with poses
    img_files = sorted(os.listdir(img_dir))
    img_files = [f for f in img_files if f.lower().endswith((".png", ".jpg", ".jpeg"))]

    imgs = []
    for fname in img_files:
        img = iio.imread(os.path.join(img_dir, fname))
        imgs.append(img)

    images = np.array(imgs, dtype=np.float32) / 255.0

    # Only keep RGB channels (discard alpha if present)
    if images.shape[-1] == 4:
        images = images[..., :3]

    # Compute intrinsics
    H_orig, W_orig, focal_orig = hwf_raw
    H = int(H_orig)
    W = int(W_orig)
    focal = float(focal_orig)

    # Downsample if requested
    if factor > 1:
        H = H // factor
        W = W // factor
        focal = focal / float(factor)

        imgs_down = np.zeros((images.shape[0], H, W, images.shape[-1]), dtype=np.float32)
        for i, img in enumerate(images):
            imgs_down[i] = _downsample_image(img, H, W)
        images = imgs_down

    return images, [H, W, focal]


def _downsample_image(img, target_h, target_w):
    """Downsample an image using block averaging.

    Args:
        img: np.ndarray, shape [H, W, C], float32.
        target_h: Target height.
        target_w: Target width.

    Returns:
        np.ndarray, shape [target_h, target_w, C], float32.
    """
    h, w, c = img.shape
    factor_h = h // target_h
    factor_w = w // target_w
    return img.reshape(target_h, factor_h, target_w, factor_w, c).mean(axis=(1, 3))


def _recenter_poses(poses):
    """Recenter poses so the average camera pose sits at the world origin.

    Computes the average pose from all cameras, then transforms all poses
    so that the average becomes the identity (centered at origin, looking
    along -Z with Y up).

    Args:
        poses: [N, 3, 4] camera-to-world matrices.

    Returns:
        poses_centered: [N, 3, 4] recentered camera-to-world matrices.
    """
    avg_pose = _average_poses(poses)

    # Build 4x4 homogeneous average pose
    avg_4x4 = np.eye(4, dtype=np.float32)
    avg_4x4[:3, :4] = avg_pose

    # Transform all poses: new_pose = inv(avg_pose) @ old_pose
    avg_inv = np.linalg.inv(avg_4x4)

    N = poses.shape[0]
    poses_centered = np.zeros_like(poses)
    for i in range(N):
        pose_4x4 = np.eye(4, dtype=np.float32)
        pose_4x4[:3, :4] = poses[i]
        new_pose = avg_inv @ pose_4x4
        poses_centered[i] = new_pose[:3, :4]

    return poses_centered


def _average_poses(poses):
    """Compute the average camera pose using the cross-product method.

    1. Average all camera positions (translation vectors).
    2. Average all camera Z-axes (backwards directions) to get mean backwards.
    3. Use cross products to build an orthonormal frame (right, up, backwards).

    Args:
        poses: [N, 3, 4] camera-to-world matrices.

    Returns:
        avg_pose: [3, 4] the average camera-to-world matrix.
    """
    # Extract axes from each pose's rotation matrix columns
    # Column 0 = right, Column 1 = up, Column 2 = backwards (+z)
    mean_backwards = poses[:, :3, 2].mean(axis=0)  # Average +z (backwards) direction
    mean_up = poses[:, :3, 1].mean(axis=0)          # Average up direction
    mean_position = poses[:, :3, 3].mean(axis=0)    # Average camera position

    # Build orthonormal axes from the averaged directions
    backwards = mean_backwards / np.linalg.norm(mean_backwards)
    # right = up × backwards (y × z = x)
    right = np.cross(mean_up, backwards)
    right = right / np.linalg.norm(right)
    # Recompute true up = backwards × right (z × x = y)
    up = np.cross(backwards, right)
    up = up / np.linalg.norm(up)

    # Assemble the average pose matrix [right | up | backwards | position]
    avg_pose = np.zeros((3, 4), dtype=np.float32)
    avg_pose[:3, 0] = right
    avg_pose[:3, 1] = up
    avg_pose[:3, 2] = backwards
    avg_pose[:3, 3] = mean_position

    return avg_pose


def _generate_spiral_poses(poses, bounds, n_frames=120, n_rotations=2):
    """Generate a smooth spiral camera path for rendering novel views.

    Creates a camera trajectory that spirals around the mean camera position,
    suitable for forward-facing scenes.

    Args:
        poses: [N, 4, 4] recentered camera-to-world matrices.
        bounds: [N, 2] depth bounds after scaling.
        n_frames: Number of frames in the spiral.
        n_rotations: Number of full rotations in the spiral.

    Returns:
        render_poses: [n_frames, 4, 4] camera-to-world matrices along the spiral.
    """
    c2w = _average_poses(poses[:, :3, :4])
    up = c2w[:3, 1]

    # Focal depth: average depth of the scene, used to place the look-at target
    close_depth, inf_depth = bounds.min() * 0.9, bounds.max() * 5.0
    dt = 0.75
    focal_depth = 1.0 / ((1.0 - dt) / close_depth + dt / inf_depth)

    # Look-at target: shift from camera position along the forward (-z) direction
    target = c2w[:3, 3] - c2w[:3, 2] * focal_depth

    # Spiral radii from the spread of training camera positions
    positions = poses[:, :3, 3]
    rads = np.percentile(np.abs(positions), 90, axis=0)
    rads = rads * 0.8

    render_poses = []
    for theta in np.linspace(0.0, 2.0 * np.pi * n_rotations, n_frames, endpoint=False):
        # Offset in the average camera's local coordinate system
        local_offset = np.array([
            np.cos(theta) * rads[0],
            -np.sin(theta) * rads[1],
            -np.sin(theta * 0.5) * rads[2] * 0.2,
        ], dtype=np.float32)

        # Transform offset to world coordinates using the average pose's rotation
        new_position = c2w[:3, 3] + c2w[:3, :3] @ local_offset

        c2w_new = _look_at(new_position, target, up)

        pose_4x4 = np.eye(4, dtype=np.float32)
        pose_4x4[:3, :4] = c2w_new
        render_poses.append(pose_4x4)

    return np.array(render_poses, dtype=np.float32)


def _look_at(camera_position, target, up):
    """Construct a camera-to-world matrix from position, target, and up vector.

    Args:
        camera_position: [3] camera location in world space.
        target: [3] point the camera looks at.
        up: [3] approximate up direction.

    Returns:
        c2w: [3, 4] camera-to-world matrix.
    """
    forward = target - camera_position
    forward = forward / np.linalg.norm(forward)

    right = np.cross(forward, up)
    right = right / np.linalg.norm(right)

    up_true = np.cross(right, forward)
    up_true = up_true / np.linalg.norm(up_true)

    c2w = np.zeros((3, 4), dtype=np.float32)
    c2w[:3, 0] = right
    c2w[:3, 1] = up_true
    c2w[:3, 2] = -forward  # NeRF convention: camera looks along -Z
    c2w[:3, 3] = camera_position

    return c2w
